#!/usr/bin/env bash
# Fail if any declared pnpm override is not actually in force in the lockfile.
#
# WHY THIS EXISTS
# Every transitive-CVE fix in this repo is a `pnpm.overrides` entry. Those entries can stop
# working with no visible signal, in three separate ways, all of which have happened here:
#
#   1. A lockfile regenerated by the wrong pnpm silently DROPS the `overrides:` block.
#      (renovatebot/renovate#43161, May 2026 - pnpm@latest moved to 11.x and Renovate
#      rewrote locks without overrides, restoring uuid@8.3.2 among others.)
#   2. Overrides declared in a workspace MEMBER are ignored - pnpm honours them only at a
#      workspace root - so they read as applied and do nothing.
#   3. A `package.json` `pnpm.overrides` block SHADOWS `pnpm-workspace.yaml` overrides, so
#      adding one entry can silently disable every other pin in the repo.
#
# A green build with a stripped override block is strictly worse than a red one: the repo
# looks patched and is not. This check makes that state fail loudly.
#
# Usage: verify-overrides.sh [root]     (defaults to the current directory)
set -uo pipefail
ROOT="${1:-.}"
status=0
checked=0

# semver-ish compare: is $1 >= $2 ?
ge() { [ "$(printf '%s\n%s\n' "$2" "$1" | sort -V | head -1)" = "$2" ]; }

while IFS= read -r lock; do
  dir=$(dirname "$lock")
  pj="$dir/package.json"
  [ -f "$pj" ] || continue

  # Overrides can live in either place. pnpm-workspace.yaml is only consulted when
  # package.json has no pnpm.overrides block (package.json wins and shadows it).
  keys=$(jq -r '(.pnpm.overrides // {}) | keys[]' "$pj" 2>/dev/null)
  src="package.json"
  if [ -z "$keys" ] && [ -f "$dir/pnpm-workspace.yaml" ]; then
    keys=$(awk '/^overrides:/{f=1;next} /^[^[:space:]]/{f=0} f && /:/ {sub(/:.*/,"");gsub(/^[[:space:]]+|['"'"'"]/,"");print}' "$dir/pnpm-workspace.yaml")
    src="pnpm-workspace.yaml"
  fi
  [ -z "$keys" ] && continue

  echo "== $dir (overrides declared in $src)"
  checked=$((checked+1))

  if ! grep -q '^overrides:' "$lock"; then
    echo "   FAIL: $lock has no 'overrides:' block — every pin in this directory is INERT."
    echo "         A lockfile regenerated by the wrong pnpm strips this silently."
    status=1
    continue
  fi

  while IFS= read -r key; do
    [ -z "$key" ] && continue
    if [ "$src" = "package.json" ]; then
      want=$(jq -r --arg k "$key" '.pnpm.overrides[$k]' "$pj")
    else
      want=$(awk -v k="$key" '/^overrides:/{f=1;next} /^[^[:space:]]/{f=0} f' "$dir/pnpm-workspace.yaml" \
             | grep -E "^[[:space:]]*['\"]?${key}['\"]?:" | head -1 | sed -E "s/.*:[[:space:]]*//; s/^['\"]//; s/['\"]$//")
    fi
    case "$want" in ">="*) ;; *) continue ;; esac   # only floors are checkable
    floor=$(printf '%s' "$want" | sed -E 's/^>=([^ ]+).*/\1/')

    # strip a parent> prefix and a trailing @<major>; scoped names keep their leading @
    pkg="${key##*>}"
    onlymajor=$(printf '%s' "$pkg" | sed -nE 's/.*@([0-9]+)$/\1/p')
    pkg=$(printf '%s' "$pkg" | sed -E 's/@[0-9]+$//')

    # scoped packages are QUOTED in the lockfile — match both forms
    vers=$(grep -oE "^  '?${pkg}@[0-9]+\.[0-9]+\.[0-9]+" "$lock" 2>/dev/null \
           | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | sort -uV)

    # A per-major key (`react-router@8`) governs ONLY that major. Comparing it against a
    # v7 install it was never meant to touch reports a break that does not exist - that
    # false positive fired on 3 of 4 repos before this filter, and a check that cries
    # wolf gets switched off.
    if [ -n "$onlymajor" ]; then
      vers=$(printf '%s\n' $vers | awk -F. -v m="$onlymajor" '$1==m')
      [ -z "$vers" ] && { echo "   ok   $key (major $onlymajor not installed here)"; continue; }
    fi

    [ -z "$vers" ] && { echo "   ok   $key (not installed here)"; continue; }

    # Compare the HIGHEST resolved version, not the lowest.
    #
    # A tree can legitimately hold two majors of the same package while the override
    # governs only one of them - finance-quest deliberately keeps
    # `test-exclude>minimatch: ^3.0.4` because minimatch 9 crashes jest, so minimatch@3
    # sits next to minimatch@10 on purpose. Requiring the LOWEST to meet the floor
    # false-fails every repo doing that, and a check that cries wolf gets disabled.
    #
    # The regression this exists to catch drops EVERY copy back below the floor (the
    # overrides block is stripped wholesale), so the max is the honest signal.
    low=$(printf '%s\n' $vers | head -1)
    high=$(printf '%s\n' $vers | tail -1)
    if ge "$high" "$floor"; then
      if [ "$low" != "$high" ] && ! ge "$low" "$floor"; then
        echo "   ok   $key >= $floor (resolved $(printf '%s' "$vers" | tr '\n' ' ') — $low is an older major kept by a narrower override)"
      else
        echo "   ok   $key >= $floor (resolved $(printf '%s' "$vers" | tr '\n' ' '))"
      fi
    else
      echo "   FAIL: $key — every resolved copy ($(printf '%s' "$vers" | tr '\n' ' ')) is BELOW its floor $floor. The override is not in force."
      status=1
    fi
  done <<< "$keys"
done < <(find "$ROOT" -name pnpm-lock.yaml -not -path '*/node_modules/*' 2>/dev/null | sort)

echo
if [ "$checked" = "0" ]; then
  echo "No pnpm overrides declared anywhere — nothing to verify."
elif [ "$status" = "0" ]; then
  echo "All declared overrides are in force."
else
  echo "One or more overrides are NOT in force. This repo is not patched the way it claims."
fi
exit "$status"
